version: "3.9"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/mlflow.db
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ./mlruns:/mlflow/artifacts
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000

  streamlit:
    build:
      context: .
      dockerfile: containers/Dockerfile.streamlit
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - mlflow

  trainer:
    build:
      context: .
      dockerfile: containers/Dockerfile.train
    container_name: training_job
    depends_on:
      - mlflow
    command: ["python", "src/train_resnet50.py"]
    volumes:
      - ./data:/app/data
      - ./models:/app/models
