FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
COPY src/ ./src/
COPY data/ ./data/
COPY models/ ./models/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["python", "src/train.py"]
