FROM python:3.10-slim

WORKDIR /app

# Copiamos los archivos necesarios
COPY requirements.txt .
COPY src/ ./src/
COPY models/ ./models/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "src/interface.py", "--server.port=8501", "--server.address=0.0.0.0"]
